from abc import abstractmethod, ABC
from pathlib import Path
from typing import Any, Mapping, Optional, Protocol, TYPE_CHECKING

import slicer
from slicer.i18n import tr as _

from CARTLib.core.LayoutManagement import LayoutHandler

if TYPE_CHECKING:
    # NOTE: this isn't perfect (this only exposes Widgets, and Slicer's QT impl
    # isn't the same as PyQT5 itself), but it's a LOT better than constant
    # cross-referencing
    import PyQt5.Qt as qt

    # Avoid a cyclic import
    from CARTLib.utils.config import DictBackedConfig


class ResourceType(Protocol):
    """
    Protocol defining all behavior required for use within CART's cohort
    editor GUI, as well as
    """
    # A unique identifier for this type internally
    id: str
    # How to display this type to the user (within GUIS)
    pretty_name: str
    # A human-readable description for this resource type; can use Markdown formatting.
    description: str = _(
        "No description for this resource type was provided!"
    )
    # Warning which should be presented to the user when this data type is being editted
    user_warning: Optional[str] = None

    @abstractmethod
    def format_for_csv(self, resource_name: str) -> str:
        """
        Format a resource name string for use within a cohort CSV file.
        """
        ...

    @abstractmethod
    def format_for_gui(self, resource_name: str) -> str:
        """
        Format a resource name string for use within GUI elements.
        """
        ...

    @abstractmethod
    def is_type(self, csv_label: str) -> bool:
        """
        Return true if the passed label (taken from a cohort CSV file)
        matches the formatting of this resource type (i.e. it could be
        generated by the `format_for_csv` function defined above)
        """

    def buildConfigGUI(
        self, task_config: "DictBackedConfig", resource_id: Optional[str] = None
    ) -> "Optional[qt.QLayout]":
        """
        Build a GUI layout for this resource; it should initialize and automatically
        update the provided task configuration when it does so.

        :param task_config: The task configuration which should be registered.
            This will match the config type produced by the task this resource is
            associated with, having all of its functionality.
        :param resource_id: The resource ID this GUI should be built for; if None,
            this is a newly created resource.
        :returns: A QT layout containing widgets which should be presented to the
            user when this resource is being modified.
        """
        return None


class DataUnitBase(ABC):

    def __init__(
        self,
        case_data: dict[str, str],
        data_path: Path,
        prior_data: dict = None,
        scene: slicer.vtkMRMLScene = slicer.mrmlScene,  # Scene is NOT optional.
        # Default scene is the global MRML scene, which is always available.
    ):
        """
        Initialize a new data unit; you may want to add additional processing in
          subclasses.

        :param case_data: The contents of the cohort file for this specific case.
          Will always contain an "uid" entry; everything else is free-form
        :param data_path: A data path. Should be treated as the "working"
          directory for anything that needs to read from files on the disk.
        :param prior_data: Data which should be used to load previously saved
          results for this case, instead of loading "from scratch".
        :param scene: A MRML scene, where nodes should be inserted into and
          managed within when the unit is in focus (actively being worked on)

        """
        # Tracking parameters
        self.data_path: Path = data_path
        self.case_data: dict[str, str] = case_data
        self.scene: slicer.vtkMRMLScene = scene

        # Resource tracking
        self.uid = case_data.get("uid", None)

        # Layout manager for this data unit;
        # as it has MRML nodes, it needs to be cleaned up on a per-unit basis.
        self._layout_handler: Optional[LayoutHandler] = None

    ## Abstract Methods ##
    @abstractmethod
    def to_dict(self) -> dict:
        """
        Export the data into the same format used to create a new DataUnit, ready
        to be saved to the cohort CSV.

        If you use this dictionary to create a new DataUnitBase instance, it should
        yield a DataUnitBase instance which is identical to this one.

        Used by the DataManger to keep the saved output csv in sync.
        """

        raise NotImplementedError("This method must be implemented in subclasses.")

    @abstractmethod
    def validate(self):
        """
        Validate the data in this DataUnitBase instance.

        This method should be implemented to ensure that the initial input data is valid.
        Raises:
            ValueError: If the data is invalid.
        """
        raise NotImplementedError("This method must be implemented in subclasses.")

    @property
    @abstractmethod
    def layout_handler(self) -> LayoutHandler:
        """
        The layout handler for this data unit; determines how the volumes
        (and/or other node types) in the scene should be displayed.
        """
        raise NotImplementedError("This method must be implemented in subclasses.")

    ## Default Methods
    def focus_gained(self):
        """
        This is called when the DataUnit is made the "focus" of the task. You should
        "reveal" any resources you are managing here by adding them back to the MRML
        scene. The layout handler will then ensure everything is displayed correctly.
        """
        pass

    def focus_lost(self):
        """
        This is called when the DataUnit is removed from the "focus" of the task. You
        should "hide" any resources you are managing here by removing them from the MRML
        scene.
        """
        pass

    def clean(self):
        """
        This method is called right before the DataUnit is deleted (due to the module
         closing, the unit falling out of cache, or Slicer closing).

        You should ensure any data managed in this data unit is removed from memory.
         Our "base" implementation attempts to do this by replicating the DataUnit
         "losing focus", but it is near certain you will need to extend this
         functionality.
        """
        # Revoke focus from the data unit first
        self.focus_lost()

        # If we have a layout handler, have it clean up after itself
        if self._layout_handler:
            self.layout_handler.clean()

    ## Dunder Methods ##
    def __del__(self):
        # When the object is garbage collected, run cleaning first
        self.clean()

    def __delete__(self, instance):
        # When the object is explicitly deleted, run cleaning first
        self.clean()


class DataUnitFactory(Protocol):
    """
    Protocol signature which matches the elements of the DataUnitBase class
    required for it to work well within CART's cohort system.
    """
    def __call__(
        self,
        case_data: dict[str, str],
        data_path: Path,
        prior_data: dict = None,
        scene: Optional[slicer.vtkMRMLScene] = None,
    ) -> DataUnitBase:
        # The "constructor"
        ...

    @abstractmethod
    def resource_types(self) -> Mapping[str, ResourceType]:
        """
        Provide a map of identifiers to the resource type they represent
        for this data unit type/factory.
        """
        ...
